### ISSUE TITLE
贡献白嫖clash   https://sub2.smallstrawberry.com/api/v1/client/subscribe?token=945c19433127c649960d06524ab49118

### ISSUE THREAD

**Issue by wangyuan0217** [ReaJason/Clash-Butler#7]
clash，流量很多，每月清零   反正就是怎么用都用不完，可能偶尔会断
![image](https://github.com/ReaJason/Clash-Butler/assets/12730214/3c035c05-6805-4da0-a80f-66c3c8395cab)

**Comment by ReaJason** [comment]
好耶，感谢分享
